services:
  postgres:
    image: postgres:16.4
    container_name: axum_postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: axum_restful
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7.2.8
    container_name: axum_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:root@axum_postgres:5432/axum_restful
    command: [ "sqlx", "migrate", "run" ]
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: axum-restful-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "4000:4000"
    env_file:
      - .env.example
    environment:
      DATABASE_URL: postgres://postgres:root@axum_postgres:5432/axum_restful
      REDIS_URL: redis://axum_redis:6379
    networks:
      - app_network

volumes:
  pg_data:
  redis_data:

networks:
  app_network:
    driver: bridge